version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-dev
    ports: 
      - "8000:8000"
    environment:
      - MONGODB_URL=mongo-db:27017
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO=INITDB_DATABASE=userdb

volumes:
  mongodb_data: